const classCell1 = document.getElementById('class1')
const classMat1 = document.querySelector('.class1')
const classCell2 = document.getElementById('class2')
const classMat2 = document.querySelector('.class2')
const classCell3 = document.getElementById('class3')
const classMat3 = document.querySelector('.class3')
const classCell4 = document.getElementById('class4')
const classMat4 = document.querySelector('.class4')
const classCell5 = document.getElementById('class5')
const classMat5 = document.querySelector('.class5')
const classCell6 = document.getElementById('class6')
const classMat6 = document.querySelector('.class6')
const scrollItem = document.querySelector('.materials')

classCell1.addEventListener('click', showClass1)
classCell2.addEventListener('click', showClass2)
classCell3.addEventListener('click', showClass3)
classCell4.addEventListener('click', showClass4)
classCell5.addEventListener('click', showClass5)
classCell6.addEventListener('click', showClass6)

function showClass1(){
    classCell1.classList.toggle('focus')
    classCell2.classList.remove('focus')
    classCell3.classList.remove('focus')
    classCell4.classList.remove('focus')
    classCell5.classList.remove('focus')
    classCell6.classList.remove('focus')
    classMat2.classList.add('hide')
    classMat3.classList.add('hide')
    classMat4.classList.add('hide')
    classMat5.classList.add('hide')
    classMat6.classList.add('hide')
    classMat1.classList.toggle('hide')
}

function showClass2(){
    classCell2.classList.toggle('focus')
    classCell1.classList.remove('focus')
    classCell3.classList.remove('focus')
    classCell4.classList.remove('focus')
    classCell5.classList.remove('focus')
    classCell6.classList.remove('focus')
    classMat1.classList.add('hide')
    classMat3.classList.add('hide')
    classMat4.classList.add('hide')
    classMat5.classList.add('hide')
    classMat6.classList.add('hide')
    classMat2.classList.toggle('hide')

}

function showClass3(){
    classCell3.classList.toggle('focus')
    classCell1.classList.remove('focus')
    classCell2.classList.remove('focus')
    classCell4.classList.remove('focus')
    classCell5.classList.remove('focus')
    classCell6.classList.remove('focus')
    classMat1.classList.add('hide')
    classMat2.classList.add('hide')
    classMat4.classList.add('hide')
    classMat5.classList.add('hide')
    classMat6.classList.add('hide')
    classMat3.classList.toggle('hide')
}

function showClass4(){
    classCell4.classList.toggle('focus')
    classCell1.classList.remove('focus')
    classCell2.classList.remove('focus')
    classCell3.classList.remove('focus')
    classCell5.classList.remove('focus')
    classCell6.classList.remove('focus')
    classMat1.classList.add('hide')
    classMat2.classList.add('hide')
    classMat3.classList.add('hide')
    classMat5.classList.add('hide')
    classMat6.classList.add('hide')
    classMat4.classList.toggle('hide')
}

function showClass5(){
    classCell5.classList.toggle('focus')
    classCell1.classList.remove('focus')
    classCell2.classList.remove('focus')
    classCell3.classList.remove('focus')
    classCell4.classList.remove('focus')
    classCell6.classList.remove('focus')
    classMat1.classList.add('hide')
    classMat2.classList.add('hide')
    classMat3.classList.add('hide')
    classMat4.classList.add('hide')
    classMat6.classList.add('hide')
    classMat5.classList.toggle('hide')
}

function showClass6(){
    classCell6.classList.toggle('focus')
    classCell1.classList.remove('focus')
    classCell2.classList.remove('focus')
    classCell3.classList.remove('focus')
    classCell4.classList.remove('focus')
    classCell5.classList.remove('focus')
    classMat1.classList.add('hide')
    classMat2.classList.add('hide')
    classMat3.classList.add('hide')
    classMat4.classList.add('hide')
    classMat5.classList.add('hide')
    classMat6.classList.toggle('hide')
}
